# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
- repo: local
  hooks:
    - id: run-unittests
      name: Run unittests
      entry: python -m unittest discover tests
      language: python
      pass_filenames: false
